function [opt,closeRequest] = insertSnippetOptionsDlg(opt)

figSize = [ 400 345+80+10+30+50 ];
fntSize = 10;
closeRequest = false;

filterModes = {'MATCH_START','MATCH_ANYWHERE'};
previewModes = {'RAW','PARSED','EMPHASIZE_PLACEHOLDERS'};

screenSize = get(0, 'ScreenSize');
h.Fig = figure( ...
    'WindowStyle', 'modal', ...
    'Position', [ 0.5*screenSize(3:4)-0.5*figSize figSize ], ...
    'DockControls', 'off', ...
    'MenuBar', 'none', ...
    'NumberTitle', 'off', ...
    'Name', 'Options');

% ---------------------------------------------------

jsonFileNames = opt.jsonFileNames;
isJsonFileEnabled = opt.isJsonFileEnabled;

hPanelSnippets = uipanel( ...
    h.Fig, ...
    'Title','Snippets', ...
    'Units','pixels', ...
    'FontSize', fntSize, ...
    'Position',[15 235+30 370 180+10+50] );

uicontrol( ...
    'Parent',hPanelSnippets, ...
    'Style','text', ...
    'String','Definition files (double-click to enable/disable):', ...
    'HorizontalAlignment','left', ...
    'FontSize', fntSize, ...
    'Position', [15 55+80+10+50 340 20] );
h.fileNameListBox = uicontrol( ...
    'Parent',hPanelSnippets, ...
    'Style','list', ...
    'String',jsonFileNames2HTML(jsonFileNames,isJsonFileEnabled), ...
    'HorizontalAlignment','left', ...
    'FontSize', fntSize, ...
    'Position', [15 32+10 340-45 25+80+50], ...
    'Callback', @fileNameListBoxCallback );
h.addFileBtn = uicontrol( ...
    'Parent',hPanelSnippets, ...
    'Style', 'pushbutton', ...
    'String', '+', ...
    'Position', [15+340-35 32+80+10+50 30 25], ...
    'Tooltip', 'Add snippet definition file.', ...
    'FontSize', 20, ...
    'Callback', @addFileBtnCallback ...
    );
h.removeFileBtn = uicontrol( ...
    'Parent',hPanelSnippets, ...
    'Style', 'pushbutton', ...
    'String', '-', ...
    'Position', [15+340-35 32+50+10+50 30 25], ...
    'Tooltip', 'Remove selected snippet definition file.', ...
    'FontSize', 20, ...
    'Callback', @removeFileBtnCallback ...
    );
h.editFileBtn = uicontrol( ...
    'Parent',hPanelSnippets, ...
    'Style', 'pushbutton', ...
    'Position', [15+340-35 32+20+10+50 30 25], ...
    'Tooltip', 'Edit selected snippet definition file in the Matlab editor.', ...
    'FontSize', fntSize, ...
    'Callback', @editBtnCallback ...
    );

h.linkBtn = uicontrol( ...
    'Parent',hPanelSnippets, ...
    'Style','pushbutton', ...
    'String','View Snippet Syntax', ...
    'TooltipString','Opens an external web browser with a link to the Visual Studio Code documentation.', ...
    'HorizontalAlignment','left', ...    
    'FontSize', fntSize, ...
    'Position', [15 15 340-45 22], ...
    'Callback',@linkBtnCallback ...
    );

img = imread('edit_16_16.png');
img = replaceWhiteColor(img,250,255*0.95*h.editFileBtn.BackgroundColor);
h.editFileBtn.CData = img;


% ---------------------------------------------------

hght = 20;
wdth = 340;
margin = 15;
offset = 30;
bottom = 4*offset + margin;

hPanelOptions = uipanel( ...
    h.Fig, ...
    'Title','Options', ...
    'Units','pixels', ...
    'FontSize', fntSize, ...
    'Position',[15 70 wdth+2*margin 5*offset+2*margin] );

uicontrol( ...
    'Parent',hPanelOptions, ...
    'Style','text', ...
    'String','Prefix filter mode', ...   
    'HorizontalAlignment','left', ...
    'FontSize', fntSize, ...
    'Position', [margin bottom-3 0.4*wdth hght] );
h.filterMode = uicontrol( ...
    'Parent',hPanelOptions, ...
    'Style','popupmenu', ...
    'String',{'Match beginning','Match anywhere'}, ...    
    'Value',find(strcmp(filterModes,opt.filterMode),1), ...
    'HorizontalAlignment','left', ...
    'FontSize', fntSize, ...
    'Position', [margin+0.4*wdth bottom 0.6*wdth hght] );
bottom = bottom - offset;

uicontrol( ...
    'Parent',hPanelOptions, ...
    'Style','text', ...
    'String','Snippet preview mode', ...   
    'HorizontalAlignment','left', ...
    'FontSize', fntSize, ...
    'Position', [margin bottom-3 0.4*wdth hght] );
h.previewMode = uicontrol( ...
    'Parent',hPanelOptions, ...
    'Style','popupmenu', ...
    'String',{'Raw','Parsed','Emphasize placeholders'}, ...    
    'Value',find(strcmp(previewModes,opt.previewMode),1), ...
    'HorizontalAlignment','left', ...
    'FontSize', fntSize, ...
    'Position', [margin+0.4*wdth bottom 0.6*wdth hght] );
bottom = bottom - offset;

h.keepWindowLoaded = uicontrol( ...
    'Parent',hPanelOptions, ...
    'Style','checkbox', ...
    'String','Keep window loaded to speed-up opening', ...
    'Value', opt.keepWindowLoaded, ...
    'HorizontalAlignment','left', ...
    'FontSize', fntSize, ...
    'Position', [margin bottom wdth hght] );
bottom = bottom - offset;

h.filterSnippetsIfTextSelected = uicontrol( ...
    'Parent',hPanelOptions, ...
    'Style','checkbox', ...
    'String','Show snippets with selected text only if text selected', ...
    'TooltipString','Show snippets using the selected text variable only if some text was selected in the active editor. Hides all other snippets in such a case.', ...
    'Value', opt.filterSnippetsIfTextSelected, ...
    'HorizontalAlignment','left', ...
    'FontSize', fntSize, ...
    'Position', [margin bottom wdth hght] );
bottom = bottom - offset;

h.deletePartiallyMatchingWordAtCaret = uicontrol( ...
    'Parent',hPanelOptions, ...
    'Style','checkbox', ...
    'String','Delete partial word match at the editor caret', ...
    'TooltipString','Inserting a snippet deletes the word at the editor caret if it matches with the snippet prefix or if it matches with the leading characters.',...
    'Value', opt.deletePartiallyMatchingWordAtCaret, ...
    'HorizontalAlignment','left', ...
    'FontSize', fntSize, ...
    'Position', [margin bottom wdth hght] );



uicontrol(...
    'Style', 'pushbutton', ...
    'Position', [85 20 100 30], ...
    'String', 'OK', ...
    'FontSize', fntSize, ...
    'Callback', @okBtnCallback ...
    );

uicontrol(...
    'Style', 'pushbutton', ...
    'Position', [210 20 100 30], ...
    'String', 'Cancel', ...
    'FontSize', fntSize, ...
    'Callback', @cancelBtnCallback ...
    );

uiwait(h.Fig); % block execution until the figure is closed


    function okBtnCallback(~,~)
        if isempty(jsonFileNames)
            warndlg('At least one definition file must be in the list.', ...
                'MATLAB Snippets Configuration');
            return
        end
        if all(~isJsonFileEnabled)
            warndlg('At least one definition file must be enabled.', ...
                'MATLAB Snippets Configuration');
            return
        end        
        opt.jsonFileNames = jsonFileNames;
        opt.isJsonFileEnabled = isJsonFileEnabled;
        opt.filterMode = filterModes{h.filterMode.Value};
        opt.previewMode = previewModes{h.previewMode.Value};
        opt.keepWindowLoaded = (h.keepWindowLoaded.Value==1);
        opt.filterSnippetsIfTextSelected = (h.filterSnippetsIfTextSelected.Value==1);
        opt.deletePartiallyMatchingWordAtCaret = (h.deletePartiallyMatchingWordAtCaret.Value==1);
        close(h.Fig);
    end


    function cancelBtnCallback(~,~)
        close(h.Fig);
    end


    function editBtnCallback(~,~)
        fullFileName = getFullFileName(true);
        if ~isempty(fullFileName)
            close(h.Fig);
            matlab.desktop.editor.openDocument(fullFileName);
            closeRequest = true;
        end
    end


    function addFileBtnCallback(~,~)
        fullFileName = getFullFileName();
        if isempty(fullFileName)        
            [file,path] = uigetfile('*.json','Select file with snippets definition');
        else
            [file,path] = uigetfile(fullFileName,'Select file with snippets definition');
        end
        if ~isequal(file,0)
            fullFileName = [path file];
            fullFileName_ = which(file);
            if strcmp(fullFileName,fullFileName_)
                % --- selected file on the Matlab search path
                fileName = file;
            else
                fileName = fullFileName;
            end           
            % --- add to the list and sort
            jsonFileNames{end+1}     = fileName;
            isJsonFileEnabled(end+1) = true;
            % ---
            [jsonFileNames,ind] = sort(jsonFileNames);
            isJsonFileEnabled = isJsonFileEnabled(ind);
            % ---
            h.fileNameListBox.String = ...
                jsonFileNames2HTML(jsonFileNames,isJsonFileEnabled);
        end        
    end


    function removeFileBtnCallback(~,~)
        if ~isempty(jsonFileNames)        
            ilist = h.fileNameListBox.Value;
            h.fileNameListBox.Value = min(length(jsonFileNames)-1,ilist);
            % ---
            jsonFileNames(ilist)     = [];
            isJsonFileEnabled(ilist) = [];
            % ---
            h.fileNameListBox.String = ...
                jsonFileNames2HTML(jsonFileNames,isJsonFileEnabled);            
        end
    end


    function fullFileName = getFullFileName(errorEnabled)
        if nargin<1
            errorEnabled = false;
        end
        if isempty(jsonFileNames)
            fullFileName = '';
        else
            ilist = h.fileNameListBox.Value;
            fileName = jsonFileNames{ilist};
            [pathstr,~,~] = fileparts(fileName);
            if isempty(pathstr)
                fullFileName = which(fileName);
                if errorEnabled && isempty(fullFileName)
                    error(['Cannot find "' fileName '" on the Matlab search path.']);
                end
            else
                fullFileName = fileName;
            end
        end
    end


    function linkBtnCallback(~,~)
        web('https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax','-browser');
    end


    function fileNameListBoxCallback(~,~,~)
        if strcmp(get(h.Fig,'selectiontype'),'open')
            % list double-click
            ilist = h.fileNameListBox.Value;
            isJsonFileEnabled(ilist) = ~isJsonFileEnabled(ilist);
            jsonFileNamesHTML = jsonFileNames2HTML(jsonFileNames,isJsonFileEnabled);
            h.fileNameListBox.String{ilist} = ...
                jsonFileNamesHTML{ilist};
        end
    end


end


function img = replaceWhiteColor(img,thr,replacementCol)
for i = 1 : size(img,1)
    for j = 1 : size(img,2)
        if all(squeeze(img(i,j,:))>=thr*ones(3,1))
            img(i,j,:) = replacementCol;
        end
    end
end
end


function jsonFileNamesHTML = jsonFileNames2HTML(jsonFileNames,isJsonFileEnabled)
jsonFileNamesHTML = jsonFileNames;
for ifile = 1 : length(jsonFileNames)
    if isJsonFileEnabled(ifile)
        prefix = '<html><body><b>';
        postfix = '</b></body></html>';       
    else
        prefix = '<html><body><font color="rgb(200,200,200)">';
        postfix = '</font></body></html>';               
    end
    jsonFileNamesHTML{ifile} = ...
        [ prefix jsonFileNames{ifile} postfix ];
end
end